### ISSUE TITLE
Pictures in the readme.md file perhaps?

### ISSUE THREAD

**Issue by eonist** [Nike-Inc/Willow#1]
Title says it all.

**Comment by cnoon** [comment]
What types of pictures @eonist? Could you be more specific?

**Comment by eonist** [comment]
Would be interesting to see an example of the logging output. Different colors specificly. I think more people would be nudged to try it if the readme.md doc had some "spiffy" screenshots. :D

**Comment by cnoon** [comment]
Thanks for clarifying @eonist...I couldn't agree more. We'll get something put together and get it added right into the README. Colorized logs are extremely helpful in big projects where you color code various loggers or different frameworks.

**Comment by cnoon** [comment]
Hi @eonist...given that this functionality has been completely removed from Xcode 8, we're going to hold off from adding this to the README. I'm filing a rdar to add support for console message modification through Xcode extensions. Hopefully we'll get some traction with Apple on that feature request.

Cheers. 🍻

**Comment by eonist** [comment]
Great effort! What about making a NSWindow that just aligns it self to the bottom when you Debug an app? It would work with OSX not sure about IOS. Or you could pivot and make it it's own app that ran in the background. Just a thought. 

Peace for now.
