### ISSUE TITLE
Support of the new Unified Logging and Tracing System for iOS and macOS

### ISSUE THREAD

**Issue by larryonoff** [Nike-Inc/Willow#11]
Is there any plans to support the new Unified Logging and Tracing System for iOS and macOS, see https://developer.apple.com/videos/play/wwdc2016/721/.

I assume that there's a branch feature/os_log_writer that is adding this support.

I'm considering the library to use for the new app and I would like having this support. I event can take a part of the implementation.

**Comment by cnoon** [comment]
Hi @larryonoff,

We are absolutely planning on supporting this in Willow! The `os_log` APIs have not yet been fully built out for Swift yet. I tried in beta 3 and it wasn't ready (some APIs are missing). I'll be trying again here in beta 4. If it still isn't fully available, I'll most likely file a radar. Once Apple fully supports the `os_log` APIs in Swift, we will be all over getting support for them built into Willow!

Cheers. 🍻

**Comment by larryonoff** [comment]
@cnoon Thank you for such a quick answer! I heard that `os_log` will be ready for the final Swift 3.0 version.
