### ISSUE TITLE
Add Logsene / Elasticsearch Writer

### ISSUE THREAD

**Issue by otisg** [Nike-Inc/Willow#12]
We use Logsene (http://sematext.com/logsene), which exposes the Elasticsearch API.  Would be nice to have a Willow Writer that can ship logs there.

**Comment by cnoon** [comment]
This feels like a VERY specific `Writer` that would probably be better left out of the core Willow library. You can easily create your own custom Writer by following the examples in the [README](https://github.com/Nike-Inc/Willow#writers).

If you end up building something robust that you feel belongs in the core library, feel free to open a PR and we'll gladly take a look.

Cheers. 🍻
