### ISSUE TITLE
Willow 2.0 not available on cocoapods

### ISSUE THREAD

**Issue by scottdelly** [Nike-Inc/Willow#17]
Hey guys, I'm super excited to start using willow, however I just ran into a small roadblock I thought you might like to know about.

Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
project 'CCRewards'

target 'CCRewards' do
    platform :ios, '8.0'
    use_frameworks!

    pod 'Willow', '~> 2.0'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end
```

Cocoapods (1.0.1) output:

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Willow (~> 2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Willow (~> 2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I ran `pod repo update` but that did not fix the issue

Willow on cocoapods.org:
https://cocoapods.org/pods/Willow
Shows version is 1.1.0

Thanks in advance for your help and all your hard work!

**Comment by scottdelly** [comment]
Workaround is to change podfile to say:
`pod 'Willow', :git => 'https://github.com/Nike-Inc/Willow.git'`

**Comment by cnoon** [comment]
First off, glad you're psyched to use it...we're psyched to have you use it! It looks like you've managed to figure out the solution which is awesome. The reason it isn't published yet is that there's a bug in CocoaPods that is blocking us from being able to push up the podspecs for `1.2.0` and `2.0.0`. Instead, you'll need to manually point to the repo as you have already figured out. 

We'll push them up as soon as the CocoaPods issue is resolved. They are actively working on fixing the issue now.

Cheers. 🍻
