### ISSUE TITLE
coloredTimestampConfiguration referenced in Readme but not in code

### ISSUE THREAD

**Issue by scottdelly** [Nike-Inc/Willow#18]
I can't find the coloredTimestampConfiguration() function in the code anywhere. Am I doing something wrong?

**Comment by cnoon** [comment]
It was removed in Willow 1.2.0 because you cannot use XcodeColors on Xcode 8. They've disabled plugins completely. If you'd like to see the colored loging functionality come back, then I'd encourage you to dupe the radar listed in #10.

Cheers. 🍻
