### ISSUE TITLE
I have some suggestions

### ISSUE THREAD

**Issue by harryzjm** [Nike-Inc/Willow#2]
Recently, I try to found a logging library written in Swift.  
Such as  **XCGLogger**, **SwiftyBeaver** can`t satisfy me.  

Talk about Willow, I must say, your shoe is very good , so your code must be good.   

First Willow dont have a way to log to file.  
Second, I think `func info(message: () -> String)` is not very good, I suggest this:  

``` swift
func lInfo(items: Any..., separator: String = " ") {
    let str = items.reduce("") { return $0 + "\($1)" + separator }
    info (str)
}
```

So it will use like `print(1, 2, "21", [1, 2, 3])`

**Comment by cnoon** [comment]
Hi @harryzjm,

Thank you for the suggestions, please keep them coming!

To your first point about logging to a file, we've considered this multiple times. The only reason we haven't actually written a `FileWriter` yet is that we have a few too many ideas on how exactly that could work. We would want to keep it simple as a general solution, yet even that has been tricky to land on. If you could open up a new issue with your specific request and some of the things you'd like to see it be able to do, that would be a great starting point for others to also provide feedback. We'll then let people +1 ideas until we gain a consensus.

As for your second suggestion, I don't feel like this type of functionality belongs in Willow itself. However, one awesome part of Swift is that you can easily extend the `Logger` to do exactly what it is you're trying to do. Check out the [Custom Log Levels](https://github.com/Nike-Inc/Willow#creating-custom-log-levels) section in the README for more details.

Cheers. 🍻

**Comment by harryzjm** [comment]
Maybe you should add @autoclosure, so it will not cache object, just like this:
`func info(@autoclosure message: () -> String)`

**Comment by AtomicCat** [comment]
Are you thinking of `@noescape` instead of `@autoclosure`? `@noescape` does what you suggest, but cannot be used in this case because the logger might be running in asynchronous mode, which does make a copy of the closure to be executed later.

**Comment by cnoon** [comment]
So I had someone reach out to me on Twitter and point out that there's a [magical way](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html#//apple_ref/doc/uid/TP40014097-CH11-ID543) to customize `autoclosures` to not `noescape` by default! When I worked through all the porting in the Swift 1.2 betas, the docs didn't exist yet. I never realized this was possible. I already have a branch that adds the following:

``` swift
public func debug(message: Void -> String) {
    logMessage(message, withLogLevel: .Debug)
}

public func debug(@autoclosure(escaping) message: Void -> String) {
    logMessage(message, withLogLevel: .Debug)
}
```

The compiler is happy with both options. This then lets you do either of the following:

``` swift
log.debug("My new fancy inline message")

log.debug {
    let foo = "bar"
    return "Some much more complicated message: \(foo)"
}
```

This is what I always wanted to be able to do in Willow, but I didn't realize the `escaping` functionality was something Apple added. #mindblown

My plan right now is to get this pushed up once I'm back from PTO. But if someone else wants to roll with this and get the changes made and update the docs, then by all means...

**Comment by AtomicCat** [comment]
Right. So no avoiding the closure copy, but some additional syntax flexibility at the call-site. Getting back to parens for simple string logging will be a nice change. Probably looks more familiar to most people.

I'll look at getting a PR in tomorrow.

Thanks @harryzjm for the suggestion!

**Comment by cnoon** [comment]
Awesome...thanks @AtomicCat! 🍻

**Comment by AtomicCat** [comment]
merged into master
