### ISSUE TITLE
OSLogWriter not compiling on macOS

### ISSUE THREAD

**Issue by infinisil** [Nike-Inc/Willow#20]
There is an unnecessary preprocessor condition surrounding the `OSLogWriter` declaration that prevents it from being compiled on macOS.

Is there any meaning behind this? I'd like to know why this has been done this way (cc @cnoon)

PR is #19

**Comment by cnoon** [comment]
Thanks for pointing this out @Infinisil and my apologies for not getting back to you sooner. The reason it was compiled out was that it didn't work in Xcode 8.0. The `os_log` functionality wasn't fully implemented on `macOS` in Swift.

I'm going to close this issue out. Please redirect all future comments to #19.
