### ISSUE TITLE
Vulnerability to deadlocks with synchronous execution method

### ISSUE THREAD

**Issue by iby** [Nike-Inc/Willow#49]
I just came across https://github.com/JohnEstropia/CoreStore/issues/304 issue, where Willow is partly to blame, specifically [these lines](https://github.com/Nike-Inc/Willow/blob/a8750591c8b5df1fabe7fe02baa28734305d512f/Source/Logger.swift#L168-L169):

```swift
lock.lock() ; defer { lock.unlock() }
logMessage(message(), with: logLevel)
```

The message shouldn't be acquired within the lock. While the recursive lock handles deadlocking, there're a many cases where people somehow manage to get them. The aforementioned case is another example.

**Comment by cnoon** [comment]
You are correct, the `message()` should not be generated inside the lock for `.synchronous` execution. While the recursive lock should handle most cases, there are some outliers that are extremely hard to track down. The only thing that needs to be locked is the actually logging to the writers to ensure logs are not mangled.

I'm going to go ahead and close this issue out and we can continue the conversation in #50.
