### ISSUE TITLE
Impossible to compile on linux

### ISSUE THREAD

**Issue by qraimbault** [Nike-Inc/Willow#51]
Hello,

The LogWriter imports without condition the os module, and uses `%@` to print strings to NSLog.

The os module and the `%@` formatter are not available in *Foundation*, therefore it is not possible to build on Linux and do some server-side swift using Willow on Linux platform.

Here is the kind of errors you get when you try:
```
/src/Lambda/.build/checkouts/Willow.git-2002761449145563439/Source/LogWriter.swift:26:8: error: no such module 'os'
import os
       ^
```
and
```
/src/Lambda/.build/checkouts/Willow.git--433062434768024296/Source/LogWriter.swift:124:34: error: argument type 'String' does not conform to expected type 'CVarArg'
        case .nslog: NSLog("%@", message)
                                 ^~~~~~~
                                         as! CVarArg
```

I suggest to add a condition on the os import using `canImport()` and around the `OSLogWriter` class.

~~About the string formatter, we can use `withCString` and `%s`.~~ Bad solution, destroys unicode char because %s forces roman charset. Replaced with the usage of NSLog without the formatter, it works.

I made a pull request (#52) implementing this, and built it on both MacOS and Linux, so these few changes make it entirely usable on Linux.

I hope I respected all the requirements, do not hesitate to tell me if I did anything wrong. Also I'm not a native english speaker and there may be some language mistakes, sorry about that.

**Comment by cnoon** [comment]
Hi @qraimbault,

Linux support is not really something on our radar at the moment as we wouldn't use it directly at Nike. I also think that's something that the core team should add support for. I'm going to close this out for now. If anyone comes across this ticket and passing and would like to see us add support for this, please file and issue to help get it on our radar.

Cheers. 🍻
